# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-12 19:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PDF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_url', models.CharField(max_length=512)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('building', 'Building'), ('failed', 'Failed'), ('done', 'Done')], default='pending', max_length=10)),
            ],
        ),
    ]
